TrackTrigger/TrackTrigger/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from NewsApp.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^$', views.home, name='home'),
    path('NewsApp/diary/', diaryPage, name='diary'),
    re_path(r'^NewsApp/diary/(?P<slug>[\w-]+)/$',diaryEntry, name = 'diaryentry'),
    path('NewsApp/images/',imagePage, name = 'image'),
    path('NewsApp/imagemodelform/', ImageModelForm, name = 'imagemodelform'),
    path('NewsApp/addimagemodelform/', addImageModelForm, name = 'addimagemodelform'),
    path('NewsApp/todolist/',ToDoPage, name = 'todolist'),
    path('NewsApp/todomodelform/', ToDoModelForm, name = 'todomodelform'),
    path('NewsApp/addtodomodelform/', addToDoModelForm, name = 'addtodomodelform'),
    path('NewsApp/diarymodelform/', DiaryModelForm, name = 'diarymodelform'),
    path('NewsApp/adddiarymodelform/', addDiaryModelForm, name = 'adddiarymodelform'),
    path('NewsApp/inventory/', InventoryPage,name = 'inventory'),
    path('NewsApp/inventorymodelform/', InventoryModelForm, name = 'inventorymodelform'),
    path('NewsApp/addinventorymodelform/', addInventoryModelForm, name = 'addinventorymodelform'),
    path('NewsApp/quantityform/', NewQuantityForm, name = 'newquantity'),
    path('NewsApp/editquantityform/', EditQuantityForm, name = 'editquantity'),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TrackTrigger/accounts/urls.py
from . import views
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    re_path(r'^signup/', views.signup_view, name = "signup"),
    #re_path(r'^login/', views.login_view, name = "login"),
    re_path(r'^logout/', views.logout_view, name = "logout"),
    path('social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^profile/', views.profile_view, name = "profile"),
    #re_path(r'^password_reset/$', auth_views.PasswordResetView, name='password_reset'),
    #re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView, name='password_reset_confirm'),
    #re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
]

TrackTrigger/api/urls.py
from django.urls import include, path
from rest_framework import routers
from knox import views as knox_views
from . import views

router = routers.DefaultRouter()
#router.register(r'heroes', views.HeroViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'diary', views.DiaryViewSet)
#router.register(r'diary/<title>', views.IndividualDiaryViewSet)
router.register(r'inventory_object', views.InventoryObjectViewSet)
router.register(r'todoitem', views.ToDoItemViewSet)
router.register(r'image_object', views.ImageObjectViewSet)
router.register(r'profile', views.ProfileViewSet)
router.register(r'phone', views.PhoneNumberStringViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('auth', include('knox.urls')),
    path('auth/register', views.RegisterAPI.as_view()),
    path('auth/login', views.LoginAPI.as_view()),
    path('auth/user', views.UserAPI.as_view()),
    path('auth/logout', knox_views.LogoutView.as_view(), name='knox_logout')
]

TrackTrigger/templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang = "en">
<head>
    <meta charset="UTF-8">
    <title>  {% block title %}   {% endblock %}  </title>
    <link rel="stylesheet" type = "text/css", href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% include 'navbar.html' %}
    <!--<a href="{% url 'accounts:logout' %}">Logout</a>-->
</head>
<body>

{% block body %}



{% endblock %}

</body>
</html>

TrackTrigger/templates/home.html
{% extends 'base_layout.html' %}

{% block body %}
<ul>
    {% if user.is_authenticated %}
       <li><form class="logout-link" action="{% url 'accounts:logout' %}"method="post">
           {% csrf_token %}
       <button type="submit">Logout</button>
       {% else %}
       <li><a href="{% url 'login' %}">Login</a></li>
       <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
       {% endif %}
</ul>
<h1>Welcome Home</h1>
{% if user.is_authenticated %}
  <p> Welcome, {{ user.username }} </p>
{% else %}
  <p>Welcome to the Homepage</p>
{% endif %}
{% endblock %}

TrackTrigger/templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'diary' %}">Diary</a></li>
        <li><a href="{% url 'inventory' %}">Inventory</a></li>
        <li><a href="{% url 'image' %}">Images</a></li>
        <li><a href="{% url 'todolist' %}">To-Do List</a></li>
        {% endif %}
    </ul>
</nav>